name: lint

on:
  - push

jobs:
  lint:
    name: lint runner
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - name: install modules
        run: yarn
      - name: eslint
        run: yarn lint
